services:
  - type: web
    name: study-app
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    region: singapore
    plan: starter
    branch: main
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        fromService:
          type: web
          name: study-app
          property: host
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
      - key: CACHE_STORE
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: database
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: error
    buildCommand: |
      # Laravel初期化コマンド（マイグレーション優先実行）
      php artisan migrate --force
      php artisan db:seed --force
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf